In [1]:
import pandas as pd

##Loading the datasets

In [3]:
df=pd.read_csv("ai_adoption_dataset.csv")
df

,country,industry,ai_tool,adoption_rate,daily_active_users,year,age_group,company_size
0,USA,Technology,ChatGPT,40.45,2461,2023,35-44,Startup
1,France,Manufacturing,Midjourney,35.72,8496,2024,18-24,Enterprise
2,Australia,Transportation,ChatGPT,13.47,8641,2024,45-54,Startup
3,UK,Manufacturing,ChatGPT,48.46,3488,2023,45-54,Enterprise
4,UK,Agriculture,Stable Diffusion,34.06,1124,2024,45-54,SME
...,...,...,...,...,...,...,...,...
144995,Australia,Agriculture,Midjourney,86.93,7921,2023,18-24,SME
144996,Germany,Education,Midjourney,51.99,6301,2024,45-54,SME
144997,USA,Finance,Stable Diffusion,47.35,4726,2023,45-54,Startup
144998,USA,Retail,ChatGPT,31.87,2481,2024,25-34,Enterprise
144999,Canada,Technology,Claude,96.84,6479,2024,35-44,Enterprise

In [16]:
df.head()

,country,industry,ai_tool,adoption_rate,daily_active_users,year,age_group,company_size
0,USA,Technology,ChatGPT,40.45,2461,2023,35-44,Startup
1,France,Manufacturing,Midjourney,35.72,8496,2024,18-24,Enterprise
2,Australia,Transportation,ChatGPT,13.47,8641,2024,45-54,Startup
3,UK,Manufacturing,ChatGPT,48.46,3488,2023,45-54,Enterprise
4,UK,Agriculture,Stable Diffusion,34.06,1124,2024,45-54,SME

In [17]:
df.tail()

,country,industry,ai_tool,adoption_rate,daily_active_users,year,age_group,company_size
144995,Australia,Agriculture,Midjourney,86.93,7921,2023,18-24,SME
144996,Germany,Education,Midjourney,51.99,6301,2024,45-54,SME
144997,USA,Finance,Stable Diffusion,47.35,4726,2023,45-54,Startup
144998,USA,Retail,ChatGPT,31.87,2481,2024,25-34,Enterprise
144999,Canada,Technology,Claude,96.84,6479,2024,35-44,Enterprise

In [18]:
df.shape

(145000, 8)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145000 entries, 0 to 144999
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   country             145000 non-null  object
 1   industry            145000 non-null  object
 2   ai_tool             145000 non-null  object
 3   adoption_rate       145000 non-null  float64
 4   daily_active_users  145000 non-null  int64
 5   year                145000 non-null  int64
 6   age_group           145000 non-null  object
 7   company_size        145000 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 8.9+ MB

In [4]:
df.describe()

       adoption_rate  daily_active_users           year
count  145000.000000       145000.000000  145000.000000
mean       49.873025         5039.302683    2023.703117
std        28.842523         2858.124918       0.456886
min         0.000000          100.000000    2023.000000
25%        24.930000         2566.000000    2023.000000
50%        49.760000         5036.000000    2024.000000
75%        74.840000         7515.000000    2024.000000
max       100.000000         9999.000000    2024.000000

In [20]:
df.columns

Index(['country', 'industry', 'ai_tool', 'adoption_rate', 'daily_active_users',
       'year', 'age_group', 'company_size'],
      dtype='object')

##Standard Validation

In [21]:
#checking null value 

df.isnull().sum()

country               0
industry              0
ai_tool               0
adoption_rate         0
daily_active_users    0
year                  0
age_group             0
company_size          0
dtype: int64

In [22]:
#checking duplicates
df.duplicated().sum()

np.int64(0)